### ISSUE TITLE
VSCode extension 

### ISSUE THREAD

**Issue by fabiofcs** [stembrino/fcs-design-system#11]
## [SPIKE] Check how to create an extension and transform the script in a VSCode extension:

- [ ] Check the best way to create a VSC extension. Using the best practices in GitHub
- [ ] Create a sample project to test

## [TASK] Create an extension project
- [ ] Move script to this project and refractory to properly fit in these extensions

Create the best tools to simplify the script usage

**Comment by stembrino** [comment]
it  was generated a script command node because it's the proper way to develop an extension:

**Comment by stembrino** [comment]
this commit: f8e234a8738d5c98f7e4e3c08d63bb454b54ed6f
